export default {
  crops: [
    { id: 'TM786', name: 'Tomatoes - Cherry / Sungold' },
    { id: 'PP670', name: 'Peppers / Sweetheart' },
    { id: 'CU403', name: 'Cucumbers / Picolino' },
    { id: 'BR189', name: 'Broccoli / Aspabroc Broccolini' },
    { id: 'MU550', name: 'Broccoli - Gai Lan / Green Pearl' },
    { id: 'SW753', name: 'Swiss Chard / Celebration' },
    { id: 'HR1090', name: 'Peppermint / Peppermint' },
    { id: '140658', name: 'Oregano' },
    { id: 'HR1019', name: 'Basil / Genovese' },
    { id: 'HR1024', name: 'Dill / Ella' },
    { id: 'HR1073', name: 'Cilantro / Santo Long Standing' },
    { id: 'PL571', name: 'Parsley / Dark Green Italian' },
    { id: 'MS504', name: 'Arugula / Astro' },
    { id: 'MS554', name: 'Arugula / Wasabi' },
    { id: 'MS565', name: 'Arugula / Ballezia' },
    { id: 'KL429', name: 'Kale / Vates Blue Scots Curled' },
    { id: 'KL431', name: 'Kale / Red Ursa' },
    { id: 'SP701', name: 'Spinach / Bloomsdale Savoy' },
    { id: 'SP714', name: 'Spinach / Renegade' },
    { id: 'SP715', name: 'Spinach / Seaside' },
    { id: 'LT509', name: 'Lettuce - Butterhead / Blushed Butter Oak' },
    { id: 'LT458', name: 'Lettuce - Butterhead / Butter Crunch' },
    { id: 'LT541', name: 'Lettuce - Iceberg / Dillon' },
    { id: 'LT456', name: 'Lettuce / Grand Rapids TBR' },
    { id: '6868800059', name: 'Lettuce / Blend - Salad Greens' },
    { id: 'FRALP', name: 'Strawberry / Alexandria - Alpine' },
    { id: 'FR820', name: 'Strawberry / Mignonette' },
    { id: 'FR850', name: 'Strawberry / Hot Pink Berri Basket' },
    { id: '5875', name: 'Strawberry / Heirloom Pineapple' },
    { id: 'AR103', name: 'Artichoke / Imperial Star' },
    { id: 'AGBASG', name: 'Basil / Genovese' },
    { id: 'AGBAST', name: 'Basil / Thai' },
    { id: 'ASPAR', name: 'Parsley / Italian' },
    { id: 'AGMINT', name: 'Mint' },
    { id: 'AGDILL', name: 'Dill' },
    { id: 'AGCHV', name: 'Chives' },
    { id: 'AGTHYM', name: 'Thyme' },
  ],
  plots: [
    {
      id: 'nursery',
      beds: [
        { id: 'dry' },
        { id: 'moist' },
      ],
    },
    {
      id: 'wall',
      beds: [
        { id: 'A1' },
        { id: 'A2' },
        { id: 'A3' },
        { id: 'A4' },
        { id: 'A5' },
        { id: 'A6' },
        { id: 'A7' },
        { id: 'B1' },
        { id: 'B2' },
        { id: 'B3' },
        { id: 'B4' },
        { id: 'B5' },
        { id: 'B6' },
        { id: 'C1' },
        { id: 'C2' },
        { id: 'C3' },
        { id: 'C4' },
        { id: 'C5' },
        { id: 'C6' },
        { id: 'C7' },
        { id: 'D1' },
        { id: 'D2' },
        { id: 'D3' },
        { id: 'D4' },
        { id: 'D5' },
        { id: 'D6' },
        { id: 'E1' },
        { id: 'E2' },
        { id: 'E3' },
        { id: 'E4' },
        { id: 'E5' },
        { id: 'E6' },
        { id: 'F1' },
        { id: 'F2' },
        { id: 'F3' },
        { id: 'F4' },
        { id: 'F5' },
        { id: 'G1' },
        { id: 'G2' },
        { id: 'G3' },
        { id: 'G4' },
        { id: 'G5' },
        { id: 'G6' },
      ],
    },
    {
      id: 'buckets',
      beds: [
        { id: 'BU1' },
        { id: 'BU2' },
        { id: 'BU3' },
      ],
    },
    {
      id: 'trough',
      beds: [
        { id: 'TR1' },
        { id: 'TR2' },
        { id: 'TR3' },
        { id: 'TR4' },
        { id: 'TR5' },
        { id: 'TR6' },
      ],
    },
    {
      id: 'aerogarden',
      beds: [
        { id: 'AG1' },
        { id: 'AG2' },
        { id: 'AG3' },
        { id: 'AG4' },
        { id: 'AG5' },
        { id: 'AG6' },
      ],
    },
  ],
  events: [
    { id: 'seed' },
    { id: 'sprout' },
    { id: 'leaf' },
    { id: 'flower' },
    { id: 'fruit' },
    { id: 'transplant' },
    { id: 'water' },
    { id: 'feed' },
    { id: 'prune' },
    { id: 'harvest' },
    { id: 'cull' },
  ],
}
